import assert from 'node:assert/strict';
import test from 'node:test';
import { register } from 'node:module';
register('./esmJsLoader.mjs', import.meta.url);
const api = await import('../src/lib/validation-v2/index.js');
function dataset(points, lines = []) { const keys = (items) => Object.fromEntries([...new Set(items.flatMap((item) => Object.keys(item.attributes)))].map((key) => [key, {}])); return { points, lines, fieldAnalysis: { points: keys(points), lines: keys(lines) } }; }
function run(data, layerId = 'a5') { return api.runGmiValidationV2({ dataset: data, layerId, datasetRevision: 'revision-a5', sourceFormat: 'gmi' }); }
function resultFor(result, ruleId) { const found = result.ruleResults.find((item) => item.rule.ruleId === ruleId); assert.ok(found, ruleId); return found; }
test('registry has unique active owners including Batch 4 hydraulic owners', () => { const rules = api.getValidationRules(); const ids = rules.map((rule) => rule.ruleId); assert.equal(new Set(ids).size, ids.length); assert(ids.includes('innmaling.line.sdr.valid')); assert(ids.includes('innmaling.line.ring-stiffness.valid')); assert(ids.includes('innmaling.line.pressure-class.valid')); assert.equal(api.validateRuleRegistry(), true); });
test('runner retains ownership, immutable compact outcomes and CHECK-aware equations', () => { const result = run(dataset([{ attributes: { Høydereferanse: 'TOPP_INNVENDIG', Tema: 'KUM' } }, { attributes: { Høydereferanse: 'UKJENT', Tema: 'KUM' } }, { attributes: { Høydereferanse: 'BAD', Tema: 'KUM' } }])); const height = resultFor(result, 'innmaling.common.height-reference.valid'); assert.deepEqual([height.passCount, height.checkCount, height.failCount], [1, 1, 1]); assert.equal(height.outcomes.length, 3); assert.deepEqual(height.outcomes.map((item) => item.state), ['PASS', 'CHECK', 'FAIL']); assert(height.outcomes.every((item) => item.objectRef.layerId === 'a5')); assert.equal(height.passCount + height.checkCount + height.failCount + height.notEvaluatedCount + height.indeterminateCount, height.evaluatedObjectCount); assert(Object.isFrozen(result)); assert(Object.isFrozen(height.outcomes)); assert.throws(() => height.outcomes.push({}), TypeError); });
test('Tema valid gate applies invalid-over-conflict precedence and keeps geometry isolated', () => { const result = run(dataset([{ attributes: { Tema: 'KUM', S_FCODE: 'BAD' } }], [{ attributes: { Tema: 'VL', S_FCODE: 'SP' } }])); const point = resultFor(result, 'innmaling.point.tema.required'); const line = resultFor(result, 'innmaling.line.tema.required'); assert.deepEqual([point.outcomes[0].state, point.outcomes[0].reasonCode], ['FAIL', 'TEMA_INVALID']); assert.deepEqual([line.outcomes[0].state, line.outcomes[0].reasonCode], ['CHECK', 'TEMA_CONFLICT']); assert.deepEqual(result.schemaFindings.map((item) => [item.geometryScope, item.state]), [['point', 'CHECK'], ['line', 'CHECK']]); assert.equal(result.outcomes.some((item) => item.reasonCode === 'SCHEMA_TEMA_SFCODE_COEXISTENCE'), false); });
test('A5 preserves ObjectRef and source ownership protections', () => { const data = dataset([{ attributes: { Høydereferanse: 'TOPP_INNVENDIG' } }]); const result = run(data); const ref = api.createGmiObjectRefs({ dataset: data, layerId: 'a5', datasetRevision: 'revision-a5', sourceFormat: 'gmi' }).pointRefs[0]; assert.throws(() => api.extractGmiObjectFieldValue({ dataset: data, layerId: 'other', datasetRevision: 'revision-a5', sourceFormat: 'gmi', schemaBinding: result.schemaBinding, objectRef: { ...ref, layerId: 'other' }, canonicalFieldId: 'heightReference' }), /layer/); assert.equal(result.sourceFieldDiagnostics.length, 0); });
