import assert from 'node:assert/strict';
import test from 'node:test';
const api = await import('../src/lib/validation-v2/index.js');
const { getDatasetRevision } = await import('../src/lib/validation-v2/datasetRevision.js');
const T='Tema', W='Bredde', K='Tykkelse', D='Avst_BunnInnvUnderUtv', Y='Anleggs\u00e5r', C='Stedfestings\u00e5rsak', F='Datafangstdato', L='Lengde', H='Utvendig_h\u00f8yde';
function run(points, lines=[], referenceDate='2026-09-09') { const keys=(items)=>Object.fromEntries([...new Set(items.flatMap(Object.keys))].map((key)=>[key,{}])); const dataset={points:points.map((attributes)=>({attributes})),lines:lines.map((attributes)=>({attributes})),fieldAnalysis:{points:keys(points),lines:keys(lines)}}; return api.runGmiValidationV2({layerId:'batch2-completion',dataset,datasetRevision:getDatasetRevision(dataset),sourceFormat:'gmi',referenceDate}); }
function state(result,index,ruleId) { return result.outcomes.find((item)=>item.objectRef.geometryScope==='point'&&item.objectRef.sourceIndex===index&&item.ruleId===ruleId)?.state; }
test('Batch 2 contextual point and history policy has deterministic boundary behavior',()=>{const r=run([{[T]:'KUM',[W]:'20',[K]:'10',[D]:'12,5',[Y]:'2026',[F]:'09.09.2026',[C]:'NYTT'},{[T]:'LOK',[W]:'19',[Y]:'0000',[F]:'08.09.2021',[C]:'UENDR'},{[T]:'STR',[W]:'20',[K]:'1',[D]:'1.0',[Y]:'1899',[F]:'01.01.1900',[C]:'UENDR'}]); assert.equal(state(r,0,'innmaling.point.width.integer'),'PASS');assert.equal(state(r,0,'innmaling.common.capture-date.required'),'PASS');assert.equal(state(r,1,'innmaling.point.width.integer'),'CHECK');assert.equal(state(r,1,'innmaling.common.installation-year.required'),'CHECK');assert.equal(state(r,2,'innmaling.point.wall-thickness.integer'),'CHECK');});
test('NYTT years compare across geometry without traversal dependence',()=>{const r=run([{[T]:'KUM',[Y]:'1899',[F]:'01.01.1900',[C]:'UENDR'}],[{[T]:'SP',[Y]:'1899',[F]:'01.01.1900',[C]:'NYTT'}]);assert.equal(state(r,0,'innmaling.common.positioning-cause.valid'),'CHECK');});
test('F07 regression matrix covers all 19 outstanding history/date cases',()=>{const year='innmaling.common.installation-year.required',date='innmaling.common.capture-date.required',cause='innmaling.common.positioning-cause.valid';const rows=[[[C,'NYTT',Y,'2026'],year,'PASS'],[[C,'NYTT',Y,'2021'],year,'PASS'],[[C,'NYTT',Y,'2020'],year,'CHECK'],[[C,'UENDR',Y,'1900'],year,'PASS'],[[C,'UENDR',Y,'1899'],year,'CHECK'],[[C,'NYTT',Y,'2027'],year,'FAIL'],[[C,'UENDR',Y,'bad'],year,'FAIL'],[[C,'NYTT'],year,'FAIL'],[[C,'UENDR'],year,'CHECK'],[[],year,'CHECK'],[[F,'09.09.2021'],date,'PASS'],[[F,'10.09.2026'],date,'FAIL'],[[F,'bad'],date,'FAIL'],[[F,'31.02.2026'],date,'FAIL'],[[Y,'2026',F,'31.12.2025'],date,'FAIL'],[[C,'UENDR'],cause,'PASS'],[[C,'BAD'],cause,'FAIL'],[[],cause,'FAIL']].map(([pairs,id,expected])=>[Object.fromEntries(Array.from({length:pairs.length/2},(_,i)=>[pairs[i*2],pairs[i*2+1]])),id,expected]);const r=run(rows.map(([a])=>a));rows.forEach(([,id,expected],i)=>assert.equal(state(r,i,id),expected));const leap=run([{[F]:'28.02.2019'},{[F]:'27.02.2019'}],[],'2024-02-29');assert.equal(state(leap,0,date),'PASS');assert.equal(state(leap,1,date),'CHECK');});
test('F08 regression matrix covers all 32 outstanding point numeric cases',()=>{const rows=[[[T,'KUM',W,'0'],'innmaling.point.width.integer','CHECK'],[[T,'KUM',W,'1'],'innmaling.point.width.integer','CHECK'],[[T,'KUM',W,'-1'],'innmaling.point.width.integer','FAIL'],[[T,'KUM',K,'10'],'innmaling.point.wall-thickness.integer','PASS'],[[T,'KUM',K,'0'],'innmaling.point.wall-thickness.integer','CHECK'],[[T,'KUM',K,'-1'],'innmaling.point.wall-thickness.integer','FAIL'],[[T,'KUM',K,'1.5'],'innmaling.point.wall-thickness.integer','FAIL'],[[T,'KUM',K,'bad'],'innmaling.point.wall-thickness.integer','FAIL'],[[T,'KUM'],'innmaling.point.wall-thickness.integer','FAIL'],[[T,'STR'],'innmaling.point.wall-thickness.integer','PASS'],[[T,'KMR'],'innmaling.point.wall-thickness.integer','PASS'],...['12','12.5','12,5'].map(v=>[[T,'KUM',D,v],'innmaling.point.bottom-distance.decimal','PASS']),...['0','0.0','0,0'].map(v=>[[T,'KUM',D,v],'innmaling.point.bottom-distance.decimal','CHECK']),...['-1','.5','1.','1e2','1E2',' 1','1 000','bad'].map(v=>[[T,'KUM',D,v],'innmaling.point.bottom-distance.decimal','FAIL']),[[], 'innmaling.point.length.integer','PASS'],[[L,'0'],'innmaling.point.length.integer','CHECK'],[[L,'10'],'innmaling.point.length.integer','CHECK'],[[L,'-1'],'innmaling.point.length.integer','FAIL'],[[],'innmaling.point.external-height.integer','PASS'],[[H,'0'],'innmaling.point.external-height.integer','CHECK'],[[H,'10'],'innmaling.point.external-height.integer','CHECK'],[[H,'-1'],'innmaling.point.external-height.integer','FAIL'],[[H,'bad'],'innmaling.point.external-height.integer','FAIL']].map(([pairs,id,expected])=>[Object.fromEntries(Array.from({length:pairs.length/2},(_,i)=>[pairs[i*2],pairs[i*2+1]])),id,expected]);const r=run(rows.map(([a])=>a));rows.forEach(([,id,expected],i)=>assert.equal(state(r,i,id),expected));});
