import assert from 'node:assert/strict';
import test from 'node:test';
const api = await import('../src/lib/validation-v2/index.js');
const { getDatasetRevision } = await import('../src/lib/validation-v2/datasetRevision.js');
const { EXPECTED_KUMFORM_VALUES, EXPECTED_BYGGEMETODE_VALUES, EXPECTED_KJEGLE_VALUES } = await import('./fixtures/validationV2GmiV32DomainValues.mjs');
const cases=[['Kumform','manholeShape','innmaling.point.manhole-shape.valid',EXPECTED_KUMFORM_VALUES],['Byggemetode','constructionMethod','innmaling.point.construction-method.valid',EXPECTED_BYGGEMETODE_VALUES],['Kjegle','cone','innmaling.point.cone.valid',EXPECTED_KJEGLE_VALUES]];
function run(attributes){const dataset={points:[{attributes}],lines:[],fieldAnalysis:{points:Object.fromEntries(Object.keys(attributes).map(k=>[k,{}])),lines:{}}};return api.runGmiValidationV2({layerId:'code-list',dataset,datasetRevision:JSON.stringify(attributes),sourceFormat:'gmi'});}
function state(attributes,id){return run(attributes).outcomes.find(x=>x.ruleId===id)?.state;}
test('low-level code-list owners retain exact independent allowed-value inventories',()=>{const rules=api.getValidationRules();for(const [,field,id,values] of cases){const rule=api.getValidationRule(id);assert.equal(rule.canonicalFieldId,field);assert.deepEqual(rule.allowedValues,values);assert.equal(new Set(rule.allowedValues).size,values.length);assert.deepEqual(rule.geometryScopes,['point']);}assert.equal(new Set(rules.map(r=>r.ruleId)).size,rules.length);});
test('Kumform contextual requiredness and suppression follow the approved Tema matrix',()=>{const [key,,id,values]=cases[0];assert.equal(state({Tema:'KUM',[key]:values[0]},id),'PASS');assert.equal(state({Tema:'KUM'},id),'FAIL');for(const tema of ['LOK','STR','KRN','KMR']){assert.equal(state({Tema:tema,[key]:values[0]},id),'CHECK');assert.equal(state({Tema:tema},id),'PASS');}assert.equal(state({[key]:values[0]},id),'NOT_EVALUATED');assert.equal(state({Tema:'KUM',[key]:'bad'},id),'FAIL');});
test('Byggemetode contextual requiredness and UK review partition follow the approved matrix',()=>{const [key,,id,values]=cases[1];assert.equal(state({Tema:'KUM',[key]:values[0]},id),'PASS');assert.equal(state({Tema:'LOK',[key]:values[0]},id),'PASS');assert.equal(state({Tema:'KUM',[key]:'UK'},id),'CHECK');for(const tema of ['KUM','LOK'])assert.equal(state({Tema:tema},id),'FAIL');for(const tema of ['STR','KMR']){assert.equal(state({Tema:tema,[key]:values[0]},id),'CHECK');assert.equal(state({Tema:tema},id),'PASS');}assert.equal(state({[key]:values[0]},id),'NOT_EVALUATED');assert.equal(state({Tema:'KUM',[key]:'bad'},id),'FAIL');});
test('Kjegle contextual requiredness, unknown behavior, and lexical failures are exact',()=>{const [key,,id,values]=cases[2];assert.equal(state({Tema:'KUM',[key]:values[0]},id),'PASS');assert.equal(state({Tema:'KUM'},id),'FAIL');for(const tema of ['LOK','STR','KRN','KMR']){assert.equal(state({Tema:tema,[key]:values[0]},id),'CHECK');assert.equal(state({Tema:tema},id),'PASS');}assert.equal(state({[key]:values[0]},id),'NOT_EVALUATED');assert.equal(state({Tema:'KUM',[key]:'bad'},id),'FAIL');});
test('Fildata retains completed Pass/Sjekk outcomes for one delivered value in different contexts',()=>{const key='Kumform',id='innmaling.point.manhole-shape.valid',value=EXPECTED_KUMFORM_VALUES[0];const dataset={points:[{attributes:{Tema:'KUM',[key]:value}},{attributes:{Tema:'LOK',[key]:value}}],lines:[],fieldAnalysis:{points:{Tema:{},[key]:{}},lines:{}}};const result=api.runGmiValidationV2({layerId:'code-fildata',dataset,datasetRevision:getDatasetRevision(dataset),sourceFormat:'gmi'});const summary=api.getValidationV2FieldDataSummary({layerId:'code-fildata',dataset,result,geometryScope:'point',canonicalFieldId:'manholeShape',ruleId:id});const rule=result.ruleResults.find(x=>x.rule.ruleId===id);assert.equal(summary.rows[0].deliveredValue,`"${value}"`);assert.equal(summary.rows[0].ruleAcceptance,'Sjekk');assert.equal(rule.passCount,1);assert.equal(rule.checkCount,1);});
