import assert from 'node:assert/strict';
import test from 'node:test';
import { register } from 'node:module';
register('./esmJsLoader.mjs', import.meta.url);
const api = await import('../src/lib/validation-v2/index.js');
const { createValidationV2Input } = await import('../src/lib/validation-v2/uiIntegration.js');
function layer(id, points) { return { id, data: { format: 'GMI', points, lines: [], fieldAnalysis: { points: { Høydereferanse: {} }, lines: {} } } }; }
function completed(input) { return api.runGmiValidationV2(input); }
test('field information composes current policy metadata', () => { const rule = api.getValidationRule('innmaling.common.height-reference.valid'); const info = api.composeFieldInformation({ canonicalFieldId: 'heightReference', geometryScope: 'point', rule }); assert.equal(info.required, true); assert.deepEqual(info.allowedValues, rule.allowedValues); assert.equal(api.composeFieldInformation({ canonicalFieldId: 'visibility', geometryScope: 'point', rule: api.getValidationRule('innmaling.common.visibility.retired') }).required, false); });
test('every active field owner has current Field Info and conditional wording', () => { for (const rule of api.getValidationRules()) { const scope=rule.geometryScopes[0]; const info=api.composeFieldInformation({canonicalFieldId:rule.canonicalFieldId,geometryScope:scope,rule}); assert(info,rule.ruleId); assert.equal(info.documentationStatus,'COMPLETE',rule.ruleId); assert.doesNotMatch(`${info.description} ${info.qualifications.map(x=>x.text).join(' ')}`,/Må rettes|Må vurderes|Ikke oppfylt|Delvis oppfylt|Oppfylt/); } assert.equal(api.composeFieldInformation({canonicalFieldId:'width',geometryScope:'point',rule:api.getValidationRule('innmaling.point.width.integer')}).requiredness,'CONDITIONAL'); assert.equal(api.composeFieldInformation({canonicalFieldId:'attachmentLink',geometryScope:'line',rule:api.getValidationRule('innmaling.point.attachment-link.policy')}).displayName,'S_HYPERLINK'); });
test('NOBB item links are fixed-origin and only generated for integer field values',()=>{assert.equal(api.getNobbItemHref('nobbVavvsNumber','00123'),'https://nobb.no/item/00123');assert.equal(api.getNobbItemHref('nobbVavvsFrameNumber','42'),'https://nobb.no/item/42');assert.equal(api.getNobbItemHref('nobbVavvsNumber','1.0'),null);assert.equal(api.getNobbItemHref('note','123'),null);});
test('Fildata is lazy, bounded, current-result-bound and uses completed contextual outcomes', () => { api.clearValidationV2FieldDataCache(); const input = createValidationV2Input(layer('field-data', [{ attributes: { Høydereferanse: 'TOPP_INNVENDIG' } }, { attributes: { Høydereferanse: 'UKJENT' } }, { attributes: { Høydereferanse: 'BAD' } }])); const result = completed(input); const summary = api.getValidationV2FieldDataSummary({ ...input, result, geometryScope: 'point', canonicalFieldId: 'heightReference', rule: api.getValidationRule('innmaling.common.height-reference.valid') }); assert.deepEqual(summary.rows.map((row) => row.ruleAcceptance).sort(), ['Feil', 'Pass', 'Sjekk']); assert.deepEqual(summary.rows.find((row) => row.ruleAcceptance === 'Sjekk').outcomeBreakdown, { Pass: 0, Sjekk: 1, Feil: 0 }); assert.equal(api.getValidationV2FieldDataCacheStats(input.dataset).size, 1); assert.throws(() => api.getValidationV2FieldDataSummary({ ...input, result: { ...result, datasetRevision: 'stale' }, geometryScope: 'point', canonicalFieldId: 'heightReference', rule: api.getValidationRule('innmaling.common.height-reference.valid') }), /current Validator/); });
test('Fildata does not assign one object outcome to equal values', () => { const input = createValidationV2Input(layer('same-value', [{ attributes: { Høydereferanse: 'UKJENT' } }, { attributes: { Høydereferanse: 'UKJENT' } }])); const result = completed(input); const summary = api.getValidationV2FieldDataSummary({ ...input, result, geometryScope: 'point', canonicalFieldId: 'heightReference', rule: api.getValidationRule('innmaling.common.height-reference.valid') }); assert.equal(summary.rows[0].count, 2); assert.deepEqual(summary.rows[0].outcomeBreakdown, { Pass: 0, Sjekk: 2, Feil: 0 }); });
