import assert from 'node:assert/strict'; import test from 'node:test';
const api=await import('../src/lib/validation-v2/index.js'); const {getDatasetRevision}=await import('../src/lib/validation-v2/datasetRevision.js');
const {getValidationV2GeometryView}=await import('../src/lib/validation-v2/uiIntegration.js');
const A='M\u00e5lemetode',Z='M\u00e5lemetodeH\u00f8yde',V='Vertikalniv\u00e5',Y='Anleggs\u00e5r',F='Datafangstdato',C='Stedfestings\u00e5rsak';
const ACTIVE=`innmaling.common.height-reference.valid innmaling.common.installation-year.required innmaling.common.measurement-method.required innmaling.common.height-measurement-method.required innmaling.common.vertical-level.required innmaling.common.capture-date.required innmaling.common.surveyed-by.required innmaling.common.case-number.required innmaling.common.horizontal-accuracy.required innmaling.common.vertical-accuracy.required innmaling.common.max-horizontal-deviation.required innmaling.common.max-vertical-deviation.required innmaling.common.positioning-condition.valid innmaling.common.positioning-cause.valid innmaling.point.tema.required innmaling.point.type.valid innmaling.point.manhole-shape.valid innmaling.point.construction-method.valid innmaling.point.cone.valid innmaling.point.type-tema.compatible innmaling.point.inside-outside.valid innmaling.point.width.integer innmaling.point.length.integer innmaling.point.wall-thickness.integer innmaling.point.external-height.integer innmaling.point.nobb-vavvs-number.integer innmaling.point.nobb-vavvs-frame-number.integer innmaling.point.owner.valid innmaling.point.access.valid innmaling.point.bottom-distance.decimal innmaling.point.note.max-length innmaling.line.wall-thickness.required innmaling.line.tema.required innmaling.line.dimension.required innmaling.line.vertical-dimension.valid innmaling.line.material.required innmaling.line.network-type.valid innmaling.line.inside-outside.valid innmaling.line.pipe-shape.valid innmaling.line.sdr.valid innmaling.line.ring-stiffness.valid innmaling.line.pressure-class.valid innmaling.common.visibility.retired innmaling.point.facility-id.informational innmaling.point.attachment-link.policy`.split(' ');
function run(points,lines=[]){const keys=x=>Object.fromEntries([...new Set(x.flatMap(a=>Object.keys(a)))].map(k=>[k,{}]));const dataset={points:points.map(attributes=>({attributes})),lines:lines.map(attributes=>({attributes})),fieldAnalysis:{points:keys(points),lines:keys(lines)}};return [dataset,api.runGmiValidationV2({layerId:'a8',dataset,datasetRevision:getDatasetRevision(dataset),sourceFormat:'gmi',referenceDate:'2026-09-09'})];}function o(r,i,id){return r.outcomes.find(x=>x.objectRef.geometryScope==='point'&&x.objectRef.sourceIndex===i&&x.ruleId===id);}function s(r,i,id){return o(r,i,id)?.state;}
test('active owner inventory is exact, unique, scoped, and includes Batch 4 hydraulic owners',()=>{const rules=api.getValidationRules();assert.deepEqual(rules.map(r=>r.ruleId),ACTIVE);assert.equal(new Set(ACTIVE).size,ACTIVE.length);assert(['innmaling.line.sdr.valid','innmaling.line.ring-stiffness.valid','innmaling.line.pressure-class.valid'].every(id=>ACTIVE.includes(id)));for(const r of rules)assert(r.geometryScopes.every(x=>x==='point'||x==='line'));assert.deepEqual(api.getValidationRule('innmaling.point.attachment-link.policy').geometryScopes,['point','line']);});
test('common required measurement outcomes own compact missing reason and exact Pass/Sjekk partitions',()=>{const [,r]=run([{[A]:'96',[Z]:'97',[V]:'OVER_GRUNN'},{[A]:'97',[Z]:'96',[V]:'UNDER_GRUNN'},{[A]:'01',[Z]:' 96',[V]:'bad'},{}]);assert.deepEqual([s(r,0,'innmaling.common.measurement-method.required'),s(r,1,'innmaling.common.measurement-method.required'),s(r,2,'innmaling.common.measurement-method.required'),s(r,3,'innmaling.common.measurement-method.required')],['PASS','CHECK','FAIL','FAIL']);assert.equal(s(r,0,'innmaling.common.height-measurement-method.required'),'CHECK');assert.equal(s(r,1,'innmaling.common.height-measurement-method.required'),'PASS');assert.equal(s(r,0,'innmaling.common.vertical-level.required'),'CHECK');assert.equal(s(r,1,'innmaling.common.vertical-level.required'),'PASS');assert.equal(o(r,3,'innmaling.common.measurement-method.required').reasonCode,'REQUIRED_VALUE_MISSING');});
test('Tema gate resolves direct/fallback, owns conflict once, and suppresses dependent contexts',()=>{const [,r]=run([{Tema:'KUM'},{S_FCODE:'KUM'},{Tema:'KUM',S_FCODE:'KUM'},{Tema:'KUM',S_FCODE:'LOK',Bredde:'20'},{Tema:'BAD',S_FCODE:'KUM'},{}]);const id='innmaling.point.tema.required';assert.deepEqual([0,1,2].map(i=>s(r,i,id)),['PASS','PASS','PASS']);assert.equal(s(r,3,id),'CHECK');assert.equal(o(r,3,id).reasonCode,'TEMA_CONFLICT');assert.equal(s(r,3,'innmaling.point.width.integer'),'NOT_EVALUATED');assert.equal(s(r,4,id),'FAIL');assert.equal(s(r,5,id),'FAIL');assert.equal(o(r,5,id).reasonCode,'TEMA_MISSING');});
test('point Tykkelse uses the contextual owner without line borrowing',()=>{const id='innmaling.point.wall-thickness.integer';const [,r]=run([{Tema:'KUM'},{Tema:'KUM',Tykkelse:'10'},{Tema:'KUM',Tykkelse:'0'},{Tema:'KUM',Tykkelse:'1.5'},{Tema:'STR'},{Tema:'STR',Tykkelse:'10'},{Tema:'KMR',Tykkelse:'10'}],[{Tykkelse:'bad'}]);assert.deepEqual([0,1,2,3,4,5,6].map(i=>s(r,i,id)),['FAIL','PASS','CHECK','FAIL','PASS','CHECK','CHECK']);assert.equal(r.ruleResults.find(x=>x.rule.ruleId===id).geometryBreakdown.line.evaluatedCount,0);});
test('Synbarhet and optional NOBB fields are completed Pass-only/optional policy owners',()=>{const [,r]=run([{Synbarhet:'anything'},{},{'NOBB-VAVVS-nr':'12','NOBB-VAVVS-nr-ramme':'13'},{'NOBB-VAVVS-nr':'bad','NOBB-VAVVS-nr-ramme':'bad'}]);assert.deepEqual([s(r,0,'innmaling.common.visibility.retired'),s(r,1,'innmaling.common.visibility.retired')],['PASS','PASS']);assert.equal(r.ruleResults.find(x=>x.rule.ruleId==='innmaling.common.visibility.retired').findings.length,0);assert.equal(s(r,2,'innmaling.point.nobb-vavvs-number.integer'),'PASS');assert.equal(s(r,3,'innmaling.point.nobb-vavvs-number.integer'),'FAIL');assert.equal(s(r,1,'innmaling.point.nobb-vavvs-frame-number.integer'),'PASS');});
test('Type contextual missingness and compatibility are policy-specific',()=>{const [,r]=run([{Tema:'DIV'},{Tema:'KUM'},{Tema:'DIV',Type:'DB11'},{Tema:'BAS',Type:'DB11'},{Tema:'KUM',Type:'BAD'},{Type:'DB11'}]);const type='innmaling.point.type.valid',compat='innmaling.point.type-tema.compatible';assert.deepEqual([0,1,2,3,4,5].map(i=>s(r,i,type)),['FAIL','CHECK','PASS','PASS','FAIL','PASS']);assert.equal(s(r,2,compat),'PASS');assert.equal(s(r,3,compat),'FAIL');assert.equal(s(r,4,compat),'NOT_EVALUATED');});
test('geometry views, unknown fields, and reconciliation retain one-run/two-tabs architecture',()=>{const clean={Tema:'KUM',Bredde:'20',Tykkelse:'10',Avst_BunnInnvUnderUtv:'12',[A]:'96',[Z]:'96',[V]:'UNDER_GRUNN',[Y]:'2026',[F]:'09.09.2026',[C]:'NYTT'};const [base,r1]=run([clean],[{[A]:'96',[Z]:'96',[V]:'UNDER_GRUNN',[Y]:'2026',[F]:'09.09.2026',[C]:'NYTT',Tema:'SP'}]);const [,r2]=run([{...clean,UNKNOWN_A8_FIELD:'x'}],[{[A]:'96',[Z]:'96',[V]:'UNDER_GRUNN',[Y]:'2026',[F]:'09.09.2026',[C]:'NYTT',Tema:'SP'}]);assert.deepEqual(r1.outcomes.map(x=>[x.ruleId,x.state]),r2.outcomes.map(x=>[x.ruleId,x.state]));assert.equal(r2.sourceFieldDiagnostics.filter(x=>x.classification==='UNKNOWN_SOURCE_FIELD').length,1);for(const rr of r1.ruleResults){assert.equal(rr.evaluatedObjectCount,rr.passCount+rr.checkCount+rr.failCount+rr.notEvaluatedCount+rr.indeterminateCount);assert.equal(rr.findings.length,rr.checkCount+rr.failCount+rr.indeterminateCount);}assert.deepEqual(getValidationV2GeometryView(r1,'point').ruleResults.map(x=>x.rule.ruleId),ACTIVE.filter(id=>api.getValidationRule(id).geometryScopes.includes('point')));assert.deepEqual(getValidationV2GeometryView(r1,'line').ruleResults.map(x=>x.rule.ruleId),ACTIVE.filter(id=>api.getValidationRule(id).geometryScopes.includes('line')));assert.equal(base.points.length,1);});
test('S_HYPERLINK line scope is evaluated without point applicability inference',()=>{const [,r]=run([],[{Tema:'SP'},{Tema:'SP',S_HYPERLINK:'opaque attachment reference'}]);const outcomes=r.outcomes.filter(x=>x.ruleId==='innmaling.point.attachment-link.policy');assert.deepEqual(outcomes.map(x=>x.state),['PASS','PASS']);assert(outcomes.every(x=>x.objectRef.geometryScope==='line'));});
test('line Material required/list policy',()=>{const [,r]=run([],[{}, {Material:'PE'}, {Material:'AN'}, {Material:'UK'}, {Material:'bad'}]);const id='innmaling.line.material.required';assert.deepEqual([0,1,2,3,4].map(i=>r.outcomes.find(x=>x.ruleId===id&&x.objectRef.sourceIndex===i)?.state),['FAIL','PASS','CHECK','CHECK','FAIL']);});
test('Material production-domain portion',()=>{const values=api.getValidationRule('innmaling.line.material.required').allowedValues;assert.equal(values.length,45);assert(values.includes('PE100-RC-PP0'));});
test('Nett_type/Rørform real-GMI lexical portion',()=>{const [,r]=run([],[{Nett_type:' O1',Rørform:'S'},{Nett_type:'O1',Rørform:'X'}]);for(const [id,states] of [['innmaling.line.network-type.valid',['FAIL','CHECK']],['innmaling.line.pipe-shape.valid',['PASS','CHECK']]])assert.deepEqual([0,1].map(i=>r.outcomes.find(x=>x.ruleId===id&&x.objectRef.sourceIndex===i)?.state),states);});
test('Nett_type eight-value behavior',()=>{const [,r]=run([],[...['F','H','O','S','O1','O2','S6','S7','BAD'].map(Nett_type=>({Nett_type}))]);const id='innmaling.line.network-type.valid';assert.deepEqual(r.outcomes.filter(x=>x.ruleId===id).map(x=>x.state),['PASS','PASS','PASS','PASS','CHECK','CHECK','CHECK','CHECK','FAIL']);});
test('Dimensjon alias/binding portion',()=>{const [,r]=run([],[{Dimensjon:'32'},{DIM:'32'}]);const id='innmaling.line.dimension.required';assert.deepEqual(r.outcomes.filter(x=>x.ruleId===id).map(x=>x.state),['PASS','FAIL']);});
