import assert from 'node:assert/strict';
import test from 'node:test';
import { register } from 'node:module';
register('./esmJsLoader.mjs', import.meta.url);
const api = await import('../src/lib/validation-v2/index.js');
function outcome(ruleId, key, value) { const data = { points: [{ attributes: { [key]: value } }], lines: [], fieldAnalysis: { points: { [key]: {} }, lines: {} } }; const result = api.runGmiValidationV2({ layerId: 'batch1', dataset: data, datasetRevision: `${ruleId}:${String(value)}`, sourceFormat: 'gmi' }); return result.outcomes.find((item) => item.ruleId === ruleId); }
test('common numeric policies preserve lexical integer grammar and policy boundaries', () => { for (const [rule, key, pass, check, beyond, beyondState] of [['innmaling.common.horizontal-accuracy.required', 'Nøyaktighet', '3', '0', '4', 'CHECK'], ['innmaling.common.vertical-accuracy.required', 'NøyaktighetHøyde', '5', '0', '6', 'CHECK'], ['innmaling.common.max-horizontal-deviation.required', 'MaksAvvikHorisontalt', '20', '0', '21', 'FAIL'], ['innmaling.common.max-vertical-deviation.required', 'MaksAvvikVertikalt', '30', '0', '31', 'FAIL']]) { assert.equal(outcome(rule, key, pass).state, 'PASS'); assert.equal(outcome(rule, key, check).state, 'CHECK'); assert.equal(outcome(rule, key, beyond).state, beyondState); assert.equal(outcome(rule, key, '1.5').reasonCode, 'VALUE_NOT_INTEGER'); } });
test('code and text policies use Pass/Sjekk/Feil without coercion', () => { assert.equal(outcome('innmaling.common.measurement-method.required', 'Målemetode', '96').state, 'PASS'); assert.equal(outcome('innmaling.common.measurement-method.required', 'Målemetode', '97').state, 'CHECK'); assert.equal(outcome('innmaling.common.height-measurement-method.required', 'MålemetodeHøyde', '97').state, 'CHECK'); assert.equal(outcome('innmaling.common.surveyed-by.required', 'Innmålt_av', '-').state, 'CHECK'); assert.equal(outcome('innmaling.common.case-number.required', 'Saksnummer', '').state, 'PASS'); assert.equal(outcome('innmaling.common.height-reference.valid', 'Høydereferanse', 'UKJENT').state, 'CHECK'); assert.equal(outcome('innmaling.common.positioning-condition.valid', 'Stedfestingsforhold', 'ÅPEN_KUM').state, 'PASS'); assert.equal(outcome('innmaling.point.owner.valid', 'Eier', 'AN').state, 'CHECK'); assert.equal(outcome('innmaling.common.visibility.retired', 'Synbarhet', 'historic').state, 'PASS'); });
test('optional Merknad and NOBB policies retain Unicode and lexical semantics', () => { assert.equal(outcome('innmaling.point.note.max-length', 'Merknad', '').state, 'PASS'); assert.equal(outcome('innmaling.point.note.max-length', 'Merknad', '😀'.repeat(255)).state, 'PASS'); assert.equal(outcome('innmaling.point.note.max-length', 'Merknad', '😀'.repeat(256)).state, 'FAIL'); assert.equal(outcome('innmaling.point.nobb-vavvs-number.integer', 'NOBB-VAVVS-nr', '').state, 'PASS'); assert.equal(outcome('innmaling.point.nobb-vavvs-number.integer', 'NOBB-VAVVS-nr', '001').state, 'PASS'); assert.equal(outcome('innmaling.point.nobb-vavvs-number.integer', 'NOBB-VAVVS-nr', '1.0').state, 'FAIL'); });
test('inside/outside remains required on both geometries', () => { const data = { points: [{ attributes: { InnvendigUtvendig: 'ID' } }], lines: [{ attributes: { InnvendigUtvendig: '' } }], fieldAnalysis: { points: { InnvendigUtvendig: {} }, lines: { InnvendigUtvendig: {} } } }; const result = api.runGmiValidationV2({ layerId: 'both', dataset: data, datasetRevision: 'both', sourceFormat: 'gmi' }); assert.equal(result.outcomes.find((item) => item.ruleId === 'innmaling.point.inside-outside.valid').state, 'PASS'); assert.equal(result.outcomes.find((item) => item.ruleId === 'innmaling.line.inside-outside.valid').state, 'FAIL'); });
