import assert from 'node:assert/strict'; import test from 'node:test';
import { readFile } from 'node:fs/promises'; import path from 'node:path';
const api=await import('../src/lib/validation-v2/index.js'); const {getDatasetRevision}=await import('../src/lib/validation-v2/datasetRevision.js');
const {GMIParser}=await import('../src/lib/parsing/gmiParser.js'); const {decodeGmiBytes}=await import('../src/lib/parsing/gmiDecoding.js');
function run(lines){const dataset={points:[],lines:lines.map(attributes=>({attributes})),fieldAnalysis:{points:{},lines:Object.fromEntries([...new Set(lines.flatMap(Object.keys))].map(k=>[k,{}]))}};return api.runGmiValidationV2({layerId:'batch3',dataset,datasetRevision:getDatasetRevision(dataset),sourceFormat:'gmi',referenceDate:'2026-09-10'});}
function states(ruleId,lines){return run(lines).outcomes.filter(x=>x.ruleId===ruleId).map(x=>x.state);}
test('Batch 3 line code lists retain exact lexical Pass/Sjekk/Feil partitions',()=>{assert.deepEqual(states('innmaling.line.network-type.valid',[{},...['F','H','O','S','O1','O2','S6','S7',' O1','o1','BAD'].map(Nett_type=>({Nett_type}))]),['FAIL','PASS','PASS','PASS','PASS','CHECK','CHECK','CHECK','CHECK','FAIL','FAIL','FAIL']);assert.deepEqual(states('innmaling.line.pipe-shape.valid',[{},...['A','E','F','R','S','T','X',' s','BAD'].map(Rørform=>({Rørform}))]),['FAIL','CHECK','PASS','PASS','PASS','PASS','PASS','CHECK','FAIL','FAIL']);});
test('Batch 3 Material is exact and all approved values are accepted',()=>{const rule=api.getValidationRule('innmaling.line.material.required');assert.equal(rule.allowedValues.length,45);assert.deepEqual(states(rule.ruleId,rule.allowedValues.map(Material=>({Material}))),rule.allowedValues.map(x=>['BET','PE','PE100','PERC','PP','PVC','PVC-O','PVC-U','SJK'].includes(x)?'PASS':'CHECK'));assert.deepEqual(states(rule.ruleId,[{}, {Material:' PE'}, {Material:'pe'}, {Material:'BAD'}]),['FAIL','FAIL','FAIL','FAIL']);});
test('Batch 3 Dimensjon is a strict line integer',()=>{assert.deepEqual(states('innmaling.line.dimension.required',[{},...['0','1','31','32','33','-1','32.0','bad',' 32','32 ','+32','1e2'].map(Dimensjon=>({Dimensjon}))]),['FAIL','CHECK','CHECK','CHECK','PASS','PASS','FAIL','FAIL','FAIL','FAIL','FAIL','FAIL','FAIL']);});
test('Batch 3 line Tykkelse accepts only plain numeric syntax and preserves precision',()=>{assert.deepEqual(states('innmaling.line.wall-thickness.required',[{},...['10','10.5','10,5','10.55','10,55','10.000','10,123','0','0,00','-0.5','.5','1.','1e2',' 10','1 000','bad'].map(Tykkelse=>({Tykkelse}))]),['FAIL','PASS','PASS','PASS','PASS','PASS','CHECK','CHECK','CHECK','CHECK','FAIL','FAIL','FAIL','FAIL','FAIL','FAIL','FAIL']);});
test('Batch 3 VertikalDimensjon uses Rørform dependency suppression and independent invalidity',()=>{const r=run([{Rørform:'S'},{Rørform:'S',VertikalDimensjon:'100'},{Rørform:'S',VertikalDimensjon:'0'},{Rørform:'E'},{Rørform:'E',VertikalDimensjon:'1'},{Rørform:'E',VertikalDimensjon:'30'},{Rørform:'E',VertikalDimensjon:'31'},{Rørform:'E',VertikalDimensjon:'500'},{Rørform:'BAD'},{Rørform:'BAD',VertikalDimensjon:'25'},{Rørform:'BAD',VertikalDimensjon:'bad'}]);const outcomes=r.outcomes.filter(x=>x.ruleId==='innmaling.line.vertical-dimension.valid');assert.deepEqual(outcomes.map(x=>x.state),['PASS','CHECK','FAIL','FAIL','CHECK','CHECK','PASS','PASS','NOT_EVALUATED','NOT_EVALUATED','FAIL']);assert.equal(outcomes[8].suppression,'PIPE_SHAPE_UNRESOLVED');});
test('Batch 3 synthetic line oracle uses decoded GMI bytes and completed contextual outcomes',async()=>{const bytes=await readFile(path.resolve('tests/fixtures/gmi-v32/valid/line-dimensions-shapes.gmi'));const dataset=new GMIParser(decodeGmiBytes(bytes)).toObject();const result=api.runGmiValidationV2({layerId:'batch3-synthetic',dataset,datasetRevision:getDatasetRevision(dataset),sourceFormat:'gmi',referenceDate:'2026-09-10'});const state=(ruleId,index)=>result.outcomes.find(x=>x.ruleId===ruleId&&x.objectRef.sourceIndex===index)?.state;assert.deepEqual([state('innmaling.line.network-type.valid',0),state('innmaling.line.network-type.valid',2),state('innmaling.line.material.required',4),state('innmaling.line.dimension.required',0),state('innmaling.line.dimension.required',2),state('innmaling.line.wall-thickness.required',3),state('innmaling.line.pipe-shape.valid',4),state('innmaling.line.vertical-dimension.valid',0),state('innmaling.line.vertical-dimension.valid',1),state('innmaling.line.vertical-dimension.valid',6)],['PASS','CHECK','CHECK','PASS','CHECK','PASS','CHECK','PASS','PASS','NOT_EVALUATED']);});
