export const VALIDATION_V2_DOCKED_FIELD_DETAIL_WIDTH_REM = 28;
export const VALIDATION_V2_DOCKED_FIELD_DETAIL_WIDTH = `${VALIDATION_V2_DOCKED_FIELD_DETAIL_WIDTH_REM}rem`;
export const VALIDATION_V2_FIELD_MODAL_MAX_WIDTH = '44rem';
