import { CaseNormalizationPolicy, GeometryScope } from '../contracts.js';

function deepFreeze(value) {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) {
      deepFreeze(child);
    }
  }
  return value;
}

const UNIQUE_CASE_ONLY = CaseNormalizationPolicy.UNIQUE_CASE_ONLY;
const POINT = GeometryScope.POINT;
const LINE = GeometryScope.LINE;
const BOTH = [POINT, LINE];
const SOURCE_AUTHORITY = 'INNMALINGSINSTRUKS_APPENDIX_A';

/**
 * Canonical semantic fields for the GMI A0 runtime foundation.
 *
 * Geometry is represented by expectedRuleScopes, never by canonical identity.
 * The arrays on every entry are frozen together with the registry.
 */
export const CANONICAL_FIELDS = deepFreeze([
  {
    canonicalFieldId: 'access',
    displayLabel: 'Adkomst',
    sourceProperty: 'Adkomst',
    directGmiSourceKey: 'Adkomst',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Rule requiredness is outside the adapter.',
  },
  {
    canonicalFieldId: 'attachmentLink',
    displayLabel: 'S_HYPERLINK',
    sourceProperty: 'S_HYPERLINK',
    directGmiSourceKey: 'S_HYPERLINK',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['S_HYPERLINK_punkt'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Use the unsuffixed key; applicability belongs to rules.',
  },
  {
    canonicalFieldId: 'captureDate',
    displayLabel: 'Datafangstdato',
    sourceProperty: 'Datafangstdato',
    directGmiSourceKey: 'Datafangstdato',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['Dato', 'DATO', 'DATOREG', 'REGDATO'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'The legacy Dato alias group is inert.',
  },
  {
    canonicalFieldId: 'caseNumber',
    displayLabel: 'Saksnummer',
    sourceProperty: 'Saksnummer',
    directGmiSourceKey: 'Saksnummer',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Direct source property only.',
  },
  {
    canonicalFieldId: 'cone',
    displayLabel: 'Kjegle',
    sourceProperty: 'Kjegle',
    directGmiSourceKey: 'Kjegle',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Object-code applicability is outside the adapter.',
  },
  {
    canonicalFieldId: 'constructionMethod',
    displayLabel: 'Byggemetode',
    sourceProperty: 'Byggemetode',
    directGmiSourceKey: 'Byggemetode',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Object-code applicability is outside the adapter.',
  },
  {
    canonicalFieldId: 'dimension',
    displayLabel: 'Dimensjon',
    sourceProperty: 'Dimensjon',
    directGmiSourceKey: 'Dimensjon',
    expectedRuleScopes: [LINE],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['DIM'],
    recognizedUnresolvedKeys: ['DIM'],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'DIMENSJON is case-only; DIM remains unresolved.',
  },
  {
    canonicalFieldId: 'externalHeight',
    displayLabel: 'Utvendig høyde',
    sourceProperty: 'Utvendig_høyde',
    directGmiSourceKey: 'Utvendig_høyde',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Applicability remains source/domain-dependent.',
  },
  {
    canonicalFieldId: 'facilityId',
    displayLabel: 'AnleggsID',
    sourceProperty: 'AnleggsID',
    directGmiSourceKey: 'AnleggsID',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'SID is not an approved GMI field alias.',
  },
  {
    canonicalFieldId: 'heightMeasurementMethod',
    displayLabel: 'MålemetodeHøyde',
    sourceProperty: 'MålemetodeHøyde',
    directGmiSourceKey: 'MålemetodeHøyde',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['H_MÅLEMETODE', 'H_MALEMETODE'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'H_* names remain disabled.',
  },
  {
    canonicalFieldId: 'heightReference',
    displayLabel: 'Høydereferanse',
    sourceProperty: 'Høydereferanse',
    directGmiSourceKey: 'Høydereferanse',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['HOYDEREFERANSE'],
    recognizedUnresolvedKeys: ['HREF'],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'HREF is observed but has unresolved semantic authority.',
  },
  {
    canonicalFieldId: 'horizontalAccuracy',
    displayLabel: 'Nøyaktighet',
    sourceProperty: 'Nøyaktighet',
    directGmiSourceKey: 'Nøyaktighet',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['NOYAKTIGHET', 'H_MÅLEMETODE', 'H_NOYAKTIGHET'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Horizontal accuracy is distinct from both height fields.',
  },
  {
    canonicalFieldId: 'innerBottomToOuterUndersideDistance',
    displayLabel: 'Avst_BunnInnvUnderUtv',
    sourceProperty: 'Avst_BunnInnvUnderUtv',
    directGmiSourceKey: 'Avst_BunnInnvUnderUtv',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Conditional applicability is outside the adapter.',
  },
  {
    canonicalFieldId: 'insideOutside',
    displayLabel: 'InnvendigUtvendig',
    sourceProperty: 'InnvendigUtvendig',
    directGmiSourceKey: 'InnvendigUtvendig',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['InnvendigUtvendig_punkt', 'InnvendigUtvendig_led'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'The unsuffixed delivered property is shared.',
  },
  {
    canonicalFieldId: 'installationYear',
    displayLabel: 'Anleggsår',
    sourceProperty: 'Anleggsår',
    directGmiSourceKey: 'Anleggsår',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Parser coercion does not define future format validation.',
  },
  {
    canonicalFieldId: 'length',
    displayLabel: 'Lengde',
    sourceProperty: 'Lengde',
    directGmiSourceKey: 'Lengde',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'This is a point property, not computed line length.',
  },
  {
    canonicalFieldId: 'manholeShape',
    displayLabel: 'Kumform',
    sourceProperty: 'Kumform',
    directGmiSourceKey: 'Kumform',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['Rørform'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Rørform is a separate canonical line field.',
  },
  {
    canonicalFieldId: 'material',
    displayLabel: 'Material',
    sourceProperty: 'Material',
    directGmiSourceKey: 'Material',
    expectedRuleScopes: [LINE],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['MATERIALE', 'MATR'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Material never classifies hydraulics in the adapter.',
  },
  {
    canonicalFieldId: 'maxHorizontalDeviation',
    displayLabel: 'MaksAvvikHorisontalt',
    sourceProperty: 'MaksAvvikHorisontalt',
    directGmiSourceKey: 'MaksAvvikHorisontalt',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Range validation is outside the adapter.',
  },
  {
    canonicalFieldId: 'maxVerticalDeviation',
    displayLabel: 'MaksAvvikVertikalt',
    sourceProperty: 'MaksAvvikVertikalt',
    directGmiSourceKey: 'MaksAvvikVertikalt',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Range validation is outside the adapter.',
  },
  {
    canonicalFieldId: 'measurementMethod',
    displayLabel: 'Målemetode',
    sourceProperty: 'Målemetode',
    directGmiSourceKey: 'Målemetode',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['MALEMETODE', 'METODE'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'XY measurement method; generic aliases remain disabled.',
  },
  {
    canonicalFieldId: 'networkType',
    displayLabel: 'Nett type',
    sourceProperty: 'Nett_type',
    directGmiSourceKey: 'Nett_type',
    expectedRuleScopes: [LINE],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['NETTTYPE'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'The underscore is semantically significant.',
  },
  {
    canonicalFieldId: 'nobbVavvsFrameNumber',
    displayLabel: 'NOBB-VAVVS-nr-ramme',
    sourceProperty: 'NOBB-VAVVS-nr-ramme',
    directGmiSourceKey: 'NOBB-VAVVS-nr-ramme',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Punctuation is part of the literal source key.',
  },
  {
    canonicalFieldId: 'nobbVavvsNumber',
    displayLabel: 'NOBB-VAVVS-nr',
    sourceProperty: 'NOBB-VAVVS-nr',
    directGmiSourceKey: 'NOBB-VAVVS-nr',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['NOBB-VAVVS-nr_punkt', 'NOBB-VAVVS-nr_led'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Use the unsuffixed source property in both contexts.',
  },
  {
    canonicalFieldId: 'note',
    displayLabel: 'Merknad',
    sourceProperty: 'Merknad',
    directGmiSourceKey: 'Merknad',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'The adapter does not trim or validate free text.',
  },
  {
    canonicalFieldId: 'owner',
    displayLabel: 'Eier',
    sourceProperty: 'Eier',
    directGmiSourceKey: 'Eier',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'EIER is safe only as a unique case form.',
  },
  {
    canonicalFieldId: 'pipeShape',
    displayLabel: 'Rørform',
    sourceProperty: 'Rørform',
    directGmiSourceKey: 'Rørform',
    expectedRuleScopes: [LINE],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['Kumform'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Kumform is a separate point field.',
  },
  {
    canonicalFieldId: 'positioningCause',
    displayLabel: 'Stedfestingsårsak',
    sourceProperty: 'Stedfestingsårsak',
    directGmiSourceKey: 'Stedfestingsårsak',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Direct source property only.',
  },
  {
    canonicalFieldId: 'positioningCondition',
    displayLabel: 'Stedfestingsforhold',
    sourceProperty: 'Stedfestingsforhold',
    directGmiSourceKey: 'Stedfestingsforhold',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Direct source property only.',
  },
  {
    canonicalFieldId: 'pressureClass',
    displayLabel: 'Trykklasse',
    sourceProperty: 'Trykklasse',
    directGmiSourceKey: 'Trykklasse',
    expectedRuleScopes: [LINE],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['PN', 'TRYKKKLASSE'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'This value never determines hydraulic class.',
  },
  {
    canonicalFieldId: 'ringStiffness',
    displayLabel: 'Ringstivhet',
    sourceProperty: 'Ringstivhet',
    directGmiSourceKey: 'Ringstivhet',
    expectedRuleScopes: [LINE],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['SN'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'This value never determines hydraulic class.',
  },
  {
    canonicalFieldId: 'sdr',
    displayLabel: 'SDR',
    sourceProperty: 'SDR',
    directGmiSourceKey: 'SDR',
    expectedRuleScopes: [LINE],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Preserve the parser value; no hydraulic classification here.',
  },
  {
    canonicalFieldId: 'surveyedBy',
    displayLabel: 'Innmålt_av',
    sourceProperty: 'Innmålt_av',
    directGmiSourceKey: 'Innmålt_av',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Underscore is part of the direct property name.',
  },
  {
    canonicalFieldId: 'tema',
    displayLabel: 'Tema',
    sourceProperty: 'Tema',
    directGmiSourceKey: 'Tema',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: ['S_FCODE'],
    disabledLegacyAliases: ['Tema_punkt', 'Tema_led', 'PTEMA', 'LTEMA', 'FCODE'],
    recognizedUnresolvedKeys: ['.P_TEMA', '.L_TEMA'],
    sourceAuthority: 'INNMALINGSINSTRUKS_APPENDIX_A_WITH_ACCEPTED_GMI_PRACTICE_FALLBACK',
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Direct Tema wins; S_FCODE is the sole accepted fallback.',
  },
  {
    canonicalFieldId: 'type',
    displayLabel: 'Type',
    sourceProperty: 'Type',
    directGmiSourceKey: 'Type',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Object-code applicability and values are rule concerns.',
  },
  {
    canonicalFieldId: 'verticalAccuracy',
    displayLabel: 'NøyaktighetHøyde',
    sourceProperty: 'NøyaktighetHøyde',
    directGmiSourceKey: 'NøyaktighetHøyde',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['H_NOYAKTIGHET'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Z accuracy is independent of horizontal accuracy.',
  },
  {
    canonicalFieldId: 'verticalDimension',
    displayLabel: 'VertikalDimensjon',
    sourceProperty: 'VertikalDimensjon',
    directGmiSourceKey: 'VertikalDimensjon',
    expectedRuleScopes: [LINE],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Applicability belongs to a later rule.',
  },
  {
    canonicalFieldId: 'verticalLevel',
    displayLabel: 'Vertikalnivå',
    sourceProperty: 'Vertikalnivå',
    directGmiSourceKey: 'Vertikalnivå',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Value-set policy is separate from field identity.',
  },
  {
    canonicalFieldId: 'visibility',
    displayLabel: 'Synbarhet',
    sourceProperty: 'Synbarhet',
    directGmiSourceKey: 'Synbarhet',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: [],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Preserve code representation evidence.',
  },
  {
    canonicalFieldId: 'wallThickness',
    displayLabel: 'Tykkelse',
    sourceProperty: 'Tykkelse',
    directGmiSourceKey: 'Tykkelse',
    expectedRuleScopes: BOTH,
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['Tykkelse_punkt', 'Tykkelse_led'],
    recognizedUnresolvedKeys: [],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Use the unsuffixed property in both contexts.',
  },
  {
    canonicalFieldId: 'width',
    displayLabel: 'Bredde',
    sourceProperty: 'Bredde',
    directGmiSourceKey: 'Bredde',
    expectedRuleScopes: [POINT],
    caseNormalizationPolicy: UNIQUE_CASE_ONLY,
    acceptedFallbackKeys: [],
    disabledLegacyAliases: ['DIAMETER', 'DIMENSJON', 'DIM', 'Dimensjon'],
    recognizedUnresolvedKeys: ['DIMENSJON', 'DIM'],
    sourceAuthority: SOURCE_AUTHORITY,
    mappingEvidenceConfidence: 'HIGH',
    notes: 'Only Bredde and its unique case form may bind point width.',
  },
]);
